/**
 * The tiny `.onnx` fixtures, shared with the Python end-to-end suite.
 *
 * They live under `sdk-python/tests/fixtures/models` and are regenerated by
 * `scripts/gen_test_models.py`. Their outputs come from `Constant` nodes, so a
 * prediction does not depend on pixel values and the expected numbers can be
 * written down exactly — the same numbers `test_e2e_onnx.py` pins. Reading the
 * same files from both suites is what makes this a parity check rather than two
 * independent ones.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** Directory holding the shared fixture models. */
const MODELS = fileURLToPath(new URL("../../../sdk-python/tests/fixtures/models/", import.meta.url));

/**
 * Read a fixture model as bytes.
 *
 * @param name File name under the fixtures directory, e.g. `"tiny_detector.onnx"`.
 * @returns The model bytes.
 */
export function model(name: string): Uint8Array {
  return new Uint8Array(readFileSync(`${MODELS}${name}`));
}

/**
 * Provider list for every session here.
 *
 * Node has no WebGPU, and pinning WASM keeps provider detection out of the
 * picture, as the Python suite pins the CPU provider.
 */
export const WASM = ["wasm"] as const;
