"""End-to-end tests against real ONNX Runtime sessions.

Every other test in this suite drives the SDK through a fake
:class:`~ort_vision_sdk.core.backend.InferenceBackend`, which proves the
decoding maths but never proves that a task can load a file, feed ONNX Runtime
a tensor it accepts, and read the outputs back. These tests close that gap
using the tiny models under ``tests/fixtures/models`` — real ``.onnx`` files
whose outputs come from ``Constant`` nodes, so the expected predictions can be
written down exactly.

The models are regenerated by ``scripts/gen_test_models.py`` (which needs
``onnx``, a dependency this package deliberately does not carry). The expected
values below are hard-coded on purpose: if a fixture changes, these tests must
be updated deliberately rather than re-deriving whatever the code now produces.

All sessions pin the CPU provider. Auto-selection would try every installed
accelerator, which turns a unit-test run into a GPU probe — slow, and noisy on
machines with ``onnxruntime-gpu`` but no TensorRT.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
from PIL import Image

from ort_vision_sdk import Classifier, Detector, Segmenter
from ort_vision_sdk.core.exceptions import LabelMapError
from ort_vision_sdk.core.session import OrtSession
from ort_vision_sdk.core.timing import STAGES

MODELS = Path(__file__).parent / "fixtures" / "models"

CPU = ["cpu"]
"""Provider list used by every test here — see the module docstring."""

DETECTOR_LABELS = ("cat", "dog", "bird")
"""Class names baked into ``tiny_detector.onnx`` metadata."""

SQUARE_BOXES = np.array(
    [
        [16.0, 16.0, 48.0, 48.0],
        [16.0, 16.0, 48.0, 48.0],
        [6.0, 28.0, 14.0, 36.0],
    ]
)
"""Expected boxes for a 64x64 input, where letterboxing is the identity.

Anchor 1 (score 0.85, class 0) is absent because it overlaps anchor 0 at
IoU 0.88; anchor 3 shares anchor 0's box but has a different class, so
per-class NMS keeps both.
"""

WIDE_BOXES = np.array(
    [
        [32.0, 0.0, 96.0, 64.0],
        [32.0, 0.0, 96.0, 64.0],
        [12.0, 24.0, 28.0, 40.0],
    ]
)
"""Expected boxes for a 128x64 image letterboxed into the model's 64x64 input.

Letterboxing scales by ``min(64/128, 64/64) = 0.5`` and pads vertically by
``(64 - 32) / 2 = 16``, so undoing it maps an input-space ``x`` to ``x / 0.5``
and an input-space ``y`` to ``(y - 16) / 0.5``, clipped to the original extent.
Hard-coding the result makes this the one test that would fail if the letterbox
geometry or its inverse drifted.
"""

EXPECTED_CLS = np.array([0, 2, 1])
EXPECTED_CONF = np.array([0.9, 0.8, 0.7])


@pytest.fixture
def detector() -> Detector:
    """A detector over ``tiny_detector.onnx``, pinned to the CPU provider."""
    return Detector(MODELS / "tiny_detector.onnx", providers=CPU)


@pytest.fixture
def square_image() -> np.ndarray:
    """A 64x64 black image — the fixture models ignore pixel values."""
    return np.zeros((64, 64, 3), dtype=np.uint8)


class TestDetectorEndToEnd:
    def test_reads_labels_and_input_size_from_the_model(self, detector: Detector) -> None:
        assert detector.labels == DETECTOR_LABELS
        assert detector.names == {0: "cat", 1: "dog", 2: "bird"}
        assert detector.num_classes == 3
        assert detector.input_size == (64, 64)

    def test_decodes_expected_boxes_on_a_square_image(
        self, detector: Detector, square_image: np.ndarray
    ) -> None:
        result = detector.predict(square_image)[0]

        assert len(result) == 3
        np.testing.assert_allclose(result.boxes.xyxy, SQUARE_BOXES)
        np.testing.assert_array_equal(result.boxes.cls, EXPECTED_CLS)
        np.testing.assert_allclose(result.boxes.conf, EXPECTED_CONF, rtol=1e-6)
        assert [d.class_name for d in result] == ["cat", "bird", "dog"]

    def test_undoes_letterbox_geometry_on_a_wide_image(self, detector: Detector) -> None:
        wide = np.zeros((64, 128, 3), dtype=np.uint8)

        result = detector.predict(wide)[0]

        np.testing.assert_allclose(result.boxes.xyxy, WIDE_BOXES)
        np.testing.assert_array_equal(result.boxes.cls, EXPECTED_CLS)
        assert result.orig_shape == (64, 128)

    def test_crops_come_from_the_original_image(self, detector: Detector) -> None:
        original = np.zeros((64, 64, 3), dtype=np.uint8)
        original[28:36, 6:14] = (10, 20, 30)

        result = detector.predict(original)[0]

        smallest = result[2]
        assert smallest.bbox.as_int_xyxy() == (6, 28, 14, 36)
        assert smallest.cropped_image.shape == (8, 8, 3)
        assert (smallest.cropped_image == (10, 20, 30)).all()

    def test_confidence_override_drops_weakest_detection(
        self, detector: Detector, square_image: np.ndarray
    ) -> None:
        result = detector.predict(square_image, conf_threshold=0.75)[0]

        np.testing.assert_array_equal(result.boxes.cls, [0, 2])

    def test_classes_filter_keeps_only_requested_ids(
        self, detector: Detector, square_image: np.ndarray
    ) -> None:
        result = detector.predict(square_image, classes=[1])[0]

        assert len(result) == 1
        assert result[0].class_name == "dog"

    def test_reports_path_for_file_input_and_none_for_array(
        self, detector: Detector, square_image: np.ndarray, tmp_path: Path
    ) -> None:
        image_path = tmp_path / "frame.png"
        Image.fromarray(square_image).save(image_path)

        assert detector.predict(str(image_path))[0].path == str(image_path)
        assert detector.predict(square_image)[0].path is None

    def test_speed_covers_every_stage(self, detector: Detector, square_image: np.ndarray) -> None:
        speed = detector.predict(square_image)[0].speed

        assert set(speed) == set(STAGES)
        assert all(value >= 0.0 for value in speed.values())
        assert speed["inference"] > 0.0

    async def test_async_predict_matches_sync(
        self, detector: Detector, square_image: np.ndarray
    ) -> None:
        expected = detector.predict(square_image)[0]

        actual = (await detector.async_predict(square_image))[0]

        np.testing.assert_allclose(actual.boxes.xyxy, expected.boxes.xyxy)
        np.testing.assert_array_equal(actual.boxes.cls, expected.boxes.cls)

    async def test_ort_async_predict_matches_sync(
        self, detector: Detector, square_image: np.ndarray
    ) -> None:
        """Exercises ORT's native ``run_async`` against a real session.

        The unit tests for this path drive a fake backend, so this is the only
        place that proves the callback bridge resolves against real ONNX
        Runtime rather than merely against our own stub.
        """
        expected = detector.predict(square_image)[0]

        actual = (await detector.ort_async_predict(square_image))[0]

        np.testing.assert_allclose(actual.boxes.xyxy, expected.boxes.xyxy)
        np.testing.assert_array_equal(actual.boxes.cls, expected.boxes.cls)
        np.testing.assert_allclose(actual.boxes.conf, expected.boxes.conf)

    def test_without_baked_names_generates_placeholder_labels(self) -> None:
        """A 3-class model carrying no ``names`` is constructible.

        The COCO preset names exactly 80 classes, so falling back to it for a
        3-class head used to raise ``Resolved 80 labels but the model has 3
        classes`` and the detector could not be built at all. A custom export
        without baked-in names is an ordinary thing to have; it comes up as
        ``class_N`` now.
        """
        model = MODELS / "tiny_detector_no_metadata.onnx"

        detector = Detector(model, providers=CPU)

        assert detector.labels == ("class_0", "class_1", "class_2")
        assert detector.predict(np.zeros((64, 64, 3), dtype=np.uint8))[0][0].class_name == "class_0"

    def test_explicit_labels_still_win_over_the_placeholder(self) -> None:
        model = MODELS / "tiny_detector_no_metadata.onnx"

        detector = Detector(model, providers=CPU, labels=["a", "b", "c"])

        assert detector.labels == ("a", "b", "c")

    def test_wrong_label_count_is_still_rejected(self) -> None:
        """The fallback is permissive; an explicit mismatch stays an error."""
        model = MODELS / "tiny_detector_no_metadata.onnx"

        with pytest.raises(LabelMapError, match="Resolved 2 labels"):
            Detector(model, providers=CPU, labels=["a", "b"])

    def test_session_metadata_exposes_export_fields(self, detector: Detector) -> None:
        metadata = detector.session.metadata

        assert metadata["task"] == "detect"
        assert metadata["imgsz"] == "[64, 64]"
        assert metadata["names"] == "{0: 'cat', 1: 'dog', 2: 'bird'}"


class TestClassifierEndToEnd:
    def test_reads_labels_and_input_size_from_the_model(self) -> None:
        classifier = Classifier(MODELS / "tiny_classifier.onnx", providers=CPU)

        assert classifier.labels == ("ant", "bee", "cow", "doe")
        assert classifier.input_size == (32, 32)

    def test_softmax_probabilities_are_exact(self) -> None:
        """Logits ``[1.0, 3.0, 0.5, 2.0]`` through softmax, computed by hand."""
        classifier = Classifier(MODELS / "tiny_classifier.onnx", providers=CPU)

        result = classifier.predict(np.zeros((32, 32, 3), dtype=np.uint8))[0]

        np.testing.assert_allclose(
            result.probs.data,
            [0.08536889, 0.63079554, 0.05177886, 0.23205669],
            rtol=1e-6,
        )
        assert result.probs.top1 == 1
        assert result.cls == 1
        assert result.name == "bee"
        assert result.conf == pytest.approx(0.63079554, rel=1e-6)

    def test_raw_scores_are_returned_when_softmax_is_disabled(self) -> None:
        classifier = Classifier(MODELS / "tiny_classifier.onnx", providers=CPU, apply_softmax=False)

        result = classifier.predict(np.zeros((32, 32, 3), dtype=np.uint8))[0]

        np.testing.assert_allclose(result.probs.data, [1.0, 3.0, 0.5, 2.0])

    async def test_async_paths_match_sync(self) -> None:
        classifier = Classifier(MODELS / "tiny_classifier.onnx", providers=CPU)
        image = np.zeros((32, 32, 3), dtype=np.uint8)
        expected = classifier.predict(image)[0].probs.data

        via_thread = (await classifier.async_predict(image))[0].probs.data
        via_ort = (await classifier.ort_async_predict(image))[0].probs.data

        np.testing.assert_allclose(via_thread, expected)
        np.testing.assert_allclose(via_ort, expected)


class TestSegmenterEndToEnd:
    def test_reads_labels_from_the_model(self) -> None:
        segmenter = Segmenter(MODELS / "tiny_segmenter.onnx", providers=CPU)

        assert segmenter.labels == ("leaf", "stem", "root")
        assert segmenter.input_size == (64, 64)

    def test_mask_follows_prototype_geometry(self) -> None:
        """Prototype 0 is ``+5`` on its top half and ``-5`` on its bottom half.

        The single instance covers the whole image with mask coefficient 0 set
        to 1.0, so its mask must be white above the midline and black below it
        after the soft mask is resized from 8x8 up to the 64x64 box.
        """
        segmenter = Segmenter(MODELS / "tiny_segmenter.onnx", providers=CPU)

        result = segmenter.predict(np.zeros((64, 64, 3), dtype=np.uint8))[0]

        assert len(result) == 1
        instance = result[0]
        assert instance.class_name == "stem"
        assert instance.confidence == pytest.approx(0.9, rel=1e-6)
        assert instance.mask.shape == (64, 64)
        assert set(np.unique(instance.mask).tolist()) <= {0, 255}
        assert (instance.mask[:28] == 255).all()
        assert (instance.mask[36:] == 0).all()

    def test_segmented_image_zeroes_pixels_outside_the_mask(self) -> None:
        segmenter = Segmenter(MODELS / "tiny_segmenter.onnx", providers=CPU)
        original = np.full((64, 64, 3), 200, dtype=np.uint8)

        instance = segmenter.predict(original)[0][0]

        assert (instance.segmented_image[:28] == 200).all()
        assert (instance.segmented_image[36:] == 0).all()

    async def test_async_paths_match_sync(self) -> None:
        segmenter = Segmenter(MODELS / "tiny_segmenter.onnx", providers=CPU)
        image = np.zeros((64, 64, 3), dtype=np.uint8)
        expected = segmenter.predict(image)[0].masks.data[0]

        via_thread = (await segmenter.async_predict(image))[0].masks.data[0]
        via_ort = (await segmenter.ort_async_predict(image))[0].masks.data[0]

        np.testing.assert_array_equal(via_thread, expected)
        np.testing.assert_array_equal(via_ort, expected)


class TestOrtSessionRoundTrip:
    """Session-level tests over an ``Identity`` model, which echoes its input."""

    @pytest.fixture
    def session(self) -> OrtSession:
        return OrtSession(MODELS / "tiny_identity.onnx", providers=CPU)

    @pytest.fixture
    def tensor(self) -> np.ndarray:
        return np.arange(1 * 3 * 4 * 4, dtype=np.float32).reshape(1, 3, 4, 4)

    def test_exposes_graph_metadata(self, session: OrtSession) -> None:
        assert session.input_name == "images"
        assert session.input_shape == (1, 3, 4, 4)
        assert session.output_names == ["echo"]
        assert session.output_shapes == [(1, 3, 4, 4)]
        assert session.providers == ["CPUExecutionProvider"]

    def test_run_echoes_the_fed_tensor(self, session: OrtSession, tensor: np.ndarray) -> None:
        outputs = session.run({"images": tensor})

        np.testing.assert_array_equal(outputs[0], tensor)

    async def test_async_run_echoes_the_fed_tensor(
        self, session: OrtSession, tensor: np.ndarray
    ) -> None:
        outputs = await session.async_run({"images": tensor})

        np.testing.assert_array_equal(outputs[0], tensor)

    async def test_ort_async_run_echoes_the_fed_tensor(
        self, session: OrtSession, tensor: np.ndarray
    ) -> None:
        outputs = await session.ort_async_run({"images": tensor})

        np.testing.assert_array_equal(outputs[0], tensor)

    async def test_ort_async_run_honours_explicit_output_names(
        self, session: OrtSession, tensor: np.ndarray
    ) -> None:
        outputs = await session.ort_async_run({"images": tensor}, output_names=["echo"])

        assert len(outputs) == 1
        np.testing.assert_array_equal(outputs[0], tensor)
